name: git actions demo
on:
  - push
jobs:
  hello-world:
   runs-on: ubuntu-latest
   steps:
    - run: echo "hello SRE"
    - name: checkout
      uses: actions/checkout@v4
    -name: setUp node
      uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
    - name: list files
      run: ls -a
